version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodatabase
    ports:
      - "27013:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nestdev
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6373:6379"
    networks:
      - nestdev
  fake-smtp:
    image: haravich/fake-smtp-server
    container_name: fake_smtp
    ports:
      - "1023:1025"
      - "1083:1080"
    networks:
      - nestdev

volumes:
  mongodb_data:
  redis_data:

networks:
  nestdev:
